form @agent_info
    label @agent_info_name
    info @agent_info_address
    info @agent_info_city
    info @agent_info_state
    info @agent_info_zipcode
    link @agent_info_work_phone
    link @agent_info_work_mobile
    link @agent_info_email